class Genres:
    Historical = "Historical"
    Adventure = "Adventure"
    Comedy = "Comedy"
    Thriller = "Thriller"
    Drama = "Drama"
    SciFi = "Sci-Fi"
    Mystery = "Mystery"
    Horror = "Horror"
    Fantasy = "Fantasy"
